// site/src/lib/DocViewer.svelte
<script lang="ts">
import { onkeypress } from "./events"

export let src: string

function onload(evt: Event) {
	// @ts-ignore
	(evt.target as HTMLIFrameElement).contentWindow.addEventListener("keypress", onkeypress)
}
// todo: replace iframe with something not as flaky
</script>

<iframe
  src="{src}"
  title="documentation viewer"
  style="width: 100%; height: 100%;"
	on:load="{onload}">Idris documentation page loading...</iframe
>

<style>
iframe {
  border: 0;
}
</style>

// site-next/src/components/DocViewer/index.tsx
import React, { useEffect } from 'react'
import styles from './styles.module.css'

interface DocViewerProps {
  src: string
}

export const DocViewer: React.FC<DocViewerProps> = ({ src }) => {
  const handleLoad = (evt: React.SyntheticEvent<HTMLIFrameElement>) => {
    const iframe = evt.target as HTMLIFrameElement
    iframe.contentWindow?.addEventListener('keypress', (e) => {
      if (e.key === '/') {
        e.preventDefault()
        document.querySelector('input')?.focus()
      }
    })
  }

  return (
    <iframe
      src={src}
      title="documentation viewer"
      className={styles.iframe}
      onLoad={handleLoad}
    >
      Idris documentation page loading...
    </iframe>
  )
}
